#!/bin/bash

scp dainboot/zig-cache/bin/BOOTAA64.efi toaster:/volume1/docker/tftp/efi/boot/BOOTAA64.efi
scp dtb/rk3399-rockpro64.dtb toaster:/volume1/docker/tftp/dtb/rockchip/
scp os/zig-cache/bin/dainkrnl toaster:/volume1/docker/tftp/
