#!/usr/local/bin/expect

spawn qemu-system-aarch64 -m 512 -accel tcg -cpu cortex-a53 -M virt,highmem=off -bios roms/u-boot-arm64-ramfb.bin -dtb dtb/qemu_arm64.dtb -serial stdio -drive file=fat:rw:target/disk,format=raw -device virtio-net-device,netdev=net0 -netdev user,id=net0 -vga none -display none -device usb-ehci -device usb-kbd -device usb-mouse -usb

expect {
	timeout { exit 1 }
	"dtb at " { send poweroff\r }
}
expect {
	timeout { exit 2 }
	"goodbye"
}
expect {
	timeout { exit 3 }
	eof
}
