#!/usr/local/bin/expect

spawn qemu-system-aarch64 -m 512 -accel $env(CI_QEMU_ACCEL) -cpu cortex-a53 -M virt,highmem=off -drive file=$env(CI_EDK2),if=pflash,format=raw,readonly -drive file=ovmf_vars.fd,if=pflash,format=raw -serial stdio -drive file=fat:rw:target/disk,format=raw -device virtio-net-device,netdev=net0 -netdev user,id=net0 -vga none -display none -device usb-ehci -device usb-kbd -device usb-mouse -usb

expect {
	timeout { exit 1 }
	"dtb at " { send poweroff\r }
}
expect {
	timeout { exit 2 }
	"goodbye"
}
expect {
	timeout { exit 3 }
	eof
}
