#!/bin/bash

rsync -av dainboot/zig-cache/bin/BOOTAA64.rockpro64.efi toaster.local:/volume1/docker/tftp/efi/boot/BOOTAA64.efi
rsync -av dainkrnl/zig-cache/bin/dainkrnl.rockpro64 toaster.local:/volume1/docker/tftp/dainkrnl.arm64
rsync -av dtb/rk3399-rockpro64.dtb toaster.local:/volume1/docker/tftp/dtb/rockchip/
